### ISSUE TITLE
when main net?

### ISSUE THREAD

**Issue by CodyDeeds** [MrToph/KingOfEos#1]
is there a date in mind?

**Comment by MrToph** [comment]
Great timing, it's live ...
Spread the word 🎈 

I'll launch it tomorrow

**Comment by CodyDeeds** [comment]
I knew it was getting close. Thanks for your work, has really validated my ego a lot. 

https://eosflare.io/tx/b55ed2642bd1407e2df4037aae5b1e42820b9d838684e7a045236a38cdb8d321
