### ISSUE TITLE
Claim History Doesn't Refresh Automatically

### ISSUE THREAD

**Issue by Crypt0Joe** [MrToph/KingOfEos#2]
These last couple games i've noticed that the claim history/price doesn't refresh automatically. I have to manually refresh the page to see the latest claims. 

Also, when the countdown timer hits zero it starts returning negative numbers until the page is refreshed. 

Finally, i believe something needs to be changed to help eliminate the use of scripts/bots. This last game you can clearly see the same users making multiple claims only seconds apart which doesn't seem humanly possible. 

You could possibly add a text field on the page that changes after each successful claim. I saw another game using this concept which i think would make this game more fair as it would require the user to manually enter the text into the memo field for their claim to be accepted.

**Comment by MrToph** [comment]
It looks like most players interact directly with the contract through `cleos` and not through the website. So anti-botting is impossible unless built directly into the smart contract, but I don't see any way to do it in the smart contract. If you have ideas, please share.
